import './globals.css'
import { Inter } from 'next/font/google'
import Nav from '@/Components/Nav'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'

const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      {/* <Script src="../Script/firstpagescript.js" strategy='lazyOnload'></Script> */}
        <Nav/>

        
        {children}
        </body>
    </html>
  )
}
